"""add is_indexed to file model

Revision ID: 4d68f81c56d3
Revises: c585dc5f54c7
Create Date: 2025-07-13 00:59:28.174579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d68f81c56d3'
down_revision: Union[str, Sequence[str], None] = 'c585dc5f54c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_indexed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_indexed')
    # ### end Alembic commands ###
